var annotated_dup =
[
    [ "exceptions", "namespaceexceptions.html", [
      [ "InvalidInstructionException", "classexceptions_1_1InvalidInstructionException.html", "classexceptions_1_1InvalidInstructionException" ]
    ] ],
    [ "shuriken", "namespaceshuriken.html", [
      [ "analysis", "namespaceshuriken_1_1analysis.html", [
        [ "dex", "namespaceshuriken_1_1analysis_1_1dex.html", [
          [ "Analysis", "classshuriken_1_1analysis_1_1dex_1_1Analysis.html", "classshuriken_1_1analysis_1_1dex_1_1Analysis" ],
          [ "BasicBlocks", "classshuriken_1_1analysis_1_1dex_1_1BasicBlocks.html", "classshuriken_1_1analysis_1_1dex_1_1BasicBlocks" ],
          [ "ClassAnalysis", "classshuriken_1_1analysis_1_1dex_1_1ClassAnalysis.html", "classshuriken_1_1analysis_1_1dex_1_1ClassAnalysis" ],
          [ "DVMBasicBlock", "classshuriken_1_1analysis_1_1dex_1_1DVMBasicBlock.html", "classshuriken_1_1analysis_1_1dex_1_1DVMBasicBlock" ],
          [ "ExternalClass", "classshuriken_1_1analysis_1_1dex_1_1ExternalClass.html", "classshuriken_1_1analysis_1_1dex_1_1ExternalClass" ],
          [ "ExternalField", "classshuriken_1_1analysis_1_1dex_1_1ExternalField.html", "classshuriken_1_1analysis_1_1dex_1_1ExternalField" ],
          [ "ExternalMethod", "classshuriken_1_1analysis_1_1dex_1_1ExternalMethod.html", "classshuriken_1_1analysis_1_1dex_1_1ExternalMethod" ],
          [ "FieldAnalysis", "classshuriken_1_1analysis_1_1dex_1_1FieldAnalysis.html", "classshuriken_1_1analysis_1_1dex_1_1FieldAnalysis" ],
          [ "MethodAnalysis", "classshuriken_1_1analysis_1_1dex_1_1MethodAnalysis.html", "classshuriken_1_1analysis_1_1dex_1_1MethodAnalysis" ],
          [ "StringAnalysis", "classshuriken_1_1analysis_1_1dex_1_1StringAnalysis.html", "classshuriken_1_1analysis_1_1dex_1_1StringAnalysis" ]
        ] ]
      ] ],
      [ "common", "namespaceshuriken_1_1common.html", [
        [ "ShurikenStream", "classshuriken_1_1common_1_1ShurikenStream.html", "classshuriken_1_1common_1_1ShurikenStream" ]
      ] ],
      [ "dex", "namespaceshuriken_1_1dex.html", [
        [ "Utils", "classshuriken_1_1dex_1_1Utils.html", null ]
      ] ],
      [ "disassembler", "namespaceshuriken_1_1disassembler.html", [
        [ "dex", "namespaceshuriken_1_1disassembler_1_1dex.html", [
          [ "_exception_data", "structshuriken_1_1disassembler_1_1dex_1_1__exception__data.html", "structshuriken_1_1disassembler_1_1dex_1_1__exception__data" ],
          [ "_handler_data", "structshuriken_1_1disassembler_1_1dex_1_1__handler__data.html", "structshuriken_1_1disassembler_1_1dex_1_1__handler__data" ],
          [ "DalvikIncorrectInstruction", "classshuriken_1_1disassembler_1_1dex_1_1DalvikIncorrectInstruction.html", "classshuriken_1_1disassembler_1_1dex_1_1DalvikIncorrectInstruction" ],
          [ "DexDisassembler", "classshuriken_1_1disassembler_1_1dex_1_1DexDisassembler.html", "classshuriken_1_1disassembler_1_1dex_1_1DexDisassembler" ],
          [ "DexOpcodes", "classshuriken_1_1disassembler_1_1dex_1_1DexOpcodes.html", "classshuriken_1_1disassembler_1_1dex_1_1DexOpcodes" ],
          [ "DisassembledMethod", "classshuriken_1_1disassembler_1_1dex_1_1DisassembledMethod.html", "classshuriken_1_1disassembler_1_1dex_1_1DisassembledMethod" ],
          [ "Disassembler", "classshuriken_1_1disassembler_1_1dex_1_1Disassembler.html", "classshuriken_1_1disassembler_1_1dex_1_1Disassembler" ],
          [ "FillArrayData", "classshuriken_1_1disassembler_1_1dex_1_1FillArrayData.html", "classshuriken_1_1disassembler_1_1dex_1_1FillArrayData" ],
          [ "Instruction", "classshuriken_1_1disassembler_1_1dex_1_1Instruction.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction" ],
          [ "Instruction00x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction00x.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction00x" ],
          [ "Instruction10t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction10t.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction10t" ],
          [ "Instruction10x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction10x.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction10x" ],
          [ "Instruction11n", "classshuriken_1_1disassembler_1_1dex_1_1Instruction11n.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction11n" ],
          [ "Instruction11x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction11x.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction11x" ],
          [ "Instruction12x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction12x.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction12x" ],
          [ "Instruction20bc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction20bc.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction20bc" ],
          [ "Instruction20t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction20t.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction20t" ],
          [ "Instruction21c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21c.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21c" ],
          [ "Instruction21h", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21h.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21h" ],
          [ "Instruction21s", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21s.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21s" ],
          [ "Instruction21t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21t.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21t" ],
          [ "Instruction22b", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22b.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22b" ],
          [ "Instruction22c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22c.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22c" ],
          [ "Instruction22cs", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22cs.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22cs" ],
          [ "Instruction22s", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22s.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22s" ],
          [ "Instruction22t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22t.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22t" ],
          [ "Instruction22x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22x.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22x" ],
          [ "Instruction23x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction23x.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction23x" ],
          [ "Instruction30t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction30t.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction30t" ],
          [ "Instruction31c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31c.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31c" ],
          [ "Instruction31i", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31i.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31i" ],
          [ "Instruction31t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31t.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31t" ],
          [ "Instruction32x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction32x.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction32x" ],
          [ "Instruction35c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction35c.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction35c" ],
          [ "Instruction3rc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction3rc.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction3rc" ],
          [ "Instruction45cc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction45cc.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction45cc" ],
          [ "Instruction4rcc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction4rcc.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction4rcc" ],
          [ "Instruction51l", "classshuriken_1_1disassembler_1_1dex_1_1Instruction51l.html", "classshuriken_1_1disassembler_1_1dex_1_1Instruction51l" ],
          [ "InstructionUtils", "classshuriken_1_1disassembler_1_1dex_1_1InstructionUtils.html", null ],
          [ "LinearSweepDisassembler", "classshuriken_1_1disassembler_1_1dex_1_1LinearSweepDisassembler.html", "classshuriken_1_1disassembler_1_1dex_1_1LinearSweepDisassembler" ],
          [ "PackedSwitch", "classshuriken_1_1disassembler_1_1dex_1_1PackedSwitch.html", "classshuriken_1_1disassembler_1_1dex_1_1PackedSwitch" ],
          [ "SparseSwitch", "classshuriken_1_1disassembler_1_1dex_1_1SparseSwitch.html", "classshuriken_1_1disassembler_1_1dex_1_1SparseSwitch" ]
        ] ]
      ] ],
      [ "parser", "namespaceshuriken_1_1parser.html", [
        [ "apk", "namespaceshuriken_1_1parser_1_1apk.html", [
          [ "Apk", "classshuriken_1_1parser_1_1apk_1_1Apk.html", "classshuriken_1_1parser_1_1apk_1_1Apk" ]
        ] ],
        [ "dex", "namespaceshuriken_1_1parser_1_1dex.html", [
          [ "AnnotationDirectoryItem", "classshuriken_1_1parser_1_1dex_1_1AnnotationDirectoryItem.html", "classshuriken_1_1parser_1_1dex_1_1AnnotationDirectoryItem" ],
          [ "AnnotationElement", "classshuriken_1_1parser_1_1dex_1_1AnnotationElement.html", "classshuriken_1_1parser_1_1dex_1_1AnnotationElement" ],
          [ "ClassDataItem", "classshuriken_1_1parser_1_1dex_1_1ClassDataItem.html", "classshuriken_1_1parser_1_1dex_1_1ClassDataItem" ],
          [ "ClassDef", "classshuriken_1_1parser_1_1dex_1_1ClassDef.html", "classshuriken_1_1parser_1_1dex_1_1ClassDef" ],
          [ "CodeItemStruct", "classshuriken_1_1parser_1_1dex_1_1CodeItemStruct.html", "classshuriken_1_1parser_1_1dex_1_1CodeItemStruct" ],
          [ "DexClasses", "classshuriken_1_1parser_1_1dex_1_1DexClasses.html", "classshuriken_1_1parser_1_1dex_1_1DexClasses" ],
          [ "DexFields", "classshuriken_1_1parser_1_1dex_1_1DexFields.html", "classshuriken_1_1parser_1_1dex_1_1DexFields" ],
          [ "DexHeader", "classshuriken_1_1parser_1_1dex_1_1DexHeader.html", "classshuriken_1_1parser_1_1dex_1_1DexHeader" ],
          [ "DexMapList", "classshuriken_1_1parser_1_1dex_1_1DexMapList.html", "classshuriken_1_1parser_1_1dex_1_1DexMapList" ],
          [ "DexMethods", "classshuriken_1_1parser_1_1dex_1_1DexMethods.html", "classshuriken_1_1parser_1_1dex_1_1DexMethods" ],
          [ "DexProtos", "classshuriken_1_1parser_1_1dex_1_1DexProtos.html", "classshuriken_1_1parser_1_1dex_1_1DexProtos" ],
          [ "DexStrings", "classshuriken_1_1parser_1_1dex_1_1DexStrings.html", "classshuriken_1_1parser_1_1dex_1_1DexStrings" ],
          [ "DexTypes", "classshuriken_1_1parser_1_1dex_1_1DexTypes.html", "classshuriken_1_1parser_1_1dex_1_1DexTypes" ],
          [ "DVMArray", "classshuriken_1_1parser_1_1dex_1_1DVMArray.html", "classshuriken_1_1parser_1_1dex_1_1DVMArray" ],
          [ "DVMClass", "classshuriken_1_1parser_1_1dex_1_1DVMClass.html", "classshuriken_1_1parser_1_1dex_1_1DVMClass" ],
          [ "DVMFundamental", "classshuriken_1_1parser_1_1dex_1_1DVMFundamental.html", "classshuriken_1_1parser_1_1dex_1_1DVMFundamental" ],
          [ "DVMType", "classshuriken_1_1parser_1_1dex_1_1DVMType.html", "classshuriken_1_1parser_1_1dex_1_1DVMType" ],
          [ "EncodedAnnotation", "classshuriken_1_1parser_1_1dex_1_1EncodedAnnotation.html", "classshuriken_1_1parser_1_1dex_1_1EncodedAnnotation" ],
          [ "EncodedArray", "classshuriken_1_1parser_1_1dex_1_1EncodedArray.html", "classshuriken_1_1parser_1_1dex_1_1EncodedArray" ],
          [ "EncodedCatchHandler", "classshuriken_1_1parser_1_1dex_1_1EncodedCatchHandler.html", "classshuriken_1_1parser_1_1dex_1_1EncodedCatchHandler" ],
          [ "EncodedField", "classshuriken_1_1parser_1_1dex_1_1EncodedField.html", "classshuriken_1_1parser_1_1dex_1_1EncodedField" ],
          [ "EncodedMethod", "classshuriken_1_1parser_1_1dex_1_1EncodedMethod.html", "classshuriken_1_1parser_1_1dex_1_1EncodedMethod" ],
          [ "EncodedTypePair", "structshuriken_1_1parser_1_1dex_1_1EncodedTypePair.html", "structshuriken_1_1parser_1_1dex_1_1EncodedTypePair" ],
          [ "EncodedValue", "classshuriken_1_1parser_1_1dex_1_1EncodedValue.html", "classshuriken_1_1parser_1_1dex_1_1EncodedValue" ],
          [ "FieldAnnotation", "structshuriken_1_1parser_1_1dex_1_1FieldAnnotation.html", "structshuriken_1_1parser_1_1dex_1_1FieldAnnotation" ],
          [ "FieldID", "classshuriken_1_1parser_1_1dex_1_1FieldID.html", "classshuriken_1_1parser_1_1dex_1_1FieldID" ],
          [ "MethodAnnotation", "structshuriken_1_1parser_1_1dex_1_1MethodAnnotation.html", "structshuriken_1_1parser_1_1dex_1_1MethodAnnotation" ],
          [ "MethodID", "classshuriken_1_1parser_1_1dex_1_1MethodID.html", "classshuriken_1_1parser_1_1dex_1_1MethodID" ],
          [ "ParameterAnnotation", "structshuriken_1_1parser_1_1dex_1_1ParameterAnnotation.html", "structshuriken_1_1parser_1_1dex_1_1ParameterAnnotation" ],
          [ "Parser", "classshuriken_1_1parser_1_1dex_1_1Parser.html", "classshuriken_1_1parser_1_1dex_1_1Parser" ],
          [ "ProtoID", "classshuriken_1_1parser_1_1dex_1_1ProtoID.html", "classshuriken_1_1parser_1_1dex_1_1ProtoID" ],
          [ "TryItem", "structshuriken_1_1parser_1_1dex_1_1TryItem.html", "structshuriken_1_1parser_1_1dex_1_1TryItem" ],
          [ "Unknown", "classshuriken_1_1parser_1_1dex_1_1Unknown.html", "classshuriken_1_1parser_1_1dex_1_1Unknown" ]
        ] ]
      ] ],
      [ "deref_iterator_range", "structshuriken_1_1deref__iterator__range.html", "structshuriken_1_1deref__iterator__range" ],
      [ "is_container_of_reference_wrapper", "structshuriken_1_1is__container__of__reference__wrapper.html", null ],
      [ "is_container_of_reference_wrapper< T, std::void_t< typename T::value_type > >", "structshuriken_1_1is__container__of__reference__wrapper_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1value__type_01_4_01_4.html", null ],
      [ "is_reference_wrapper", "structshuriken_1_1is__reference__wrapper.html", null ],
      [ "is_reference_wrapper< std::reference_wrapper< U > >", "structshuriken_1_1is__reference__wrapper_3_01std_1_1reference__wrapper_3_01U_01_4_01_4.html", null ],
      [ "iterator_range", "classshuriken_1_1iterator__range.html", "classshuriken_1_1iterator__range" ],
      [ "Scoped", "classshuriken_1_1Scoped.html", "classshuriken_1_1Scoped" ]
    ] ],
    [ "basic_blocks_t_", "structbasic__blocks__t__.html", "structbasic__blocks__t__" ],
    [ "dvmdisassembled_method_t_", "structdvmdisassembled__method__t__.html", "structdvmdisassembled__method__t__" ],
    [ "dvmexceptions_data_t_", "structdvmexceptions__data__t__.html", "structdvmexceptions__data__t__" ],
    [ "dvmhandler_data_t_", "structdvmhandler__data__t__.html", "structdvmhandler__data__t__" ],
    [ "hdvm_class_field_idx_t_", "structhdvm__class__field__idx__t__.html", "structhdvm__class__field__idx__t__" ],
    [ "hdvm_class_idx_t_", "structhdvm__class__idx__t__.html", "structhdvm__class__idx__t__" ],
    [ "hdvm_class_method_idx_t_", "structhdvm__class__method__idx__t__.html", "structhdvm__class__method__idx__t__" ],
    [ "hdvm_classxref_t_", "structhdvm__classxref__t__.html", "structhdvm__classxref__t__" ],
    [ "hdvm_method_idx_t_", "structhdvm__method__idx__t__.html", "structhdvm__method__idx__t__" ],
    [ "hdvm_reftype_method_idx_t_", "structhdvm__reftype__method__idx__t__.html", "structhdvm__reftype__method__idx__t__" ],
    [ "hdvmbasicblock_t_", "structhdvmbasicblock__t__.html", "structhdvmbasicblock__t__" ],
    [ "hdvmclass_t", "structhdvmclass__t.html", "structhdvmclass__t" ],
    [ "hdvmclassanalysis_t_", "structhdvmclassanalysis__t__.html", "structhdvmclassanalysis__t__" ],
    [ "hdvmfield_t_", "structhdvmfield__t__.html", "structhdvmfield__t__" ],
    [ "hdvmfieldanalysis_t_", "structhdvmfieldanalysis__t__.html", "structhdvmfieldanalysis__t__" ],
    [ "hdvminstruction_t_", "structhdvminstruction__t__.html", "structhdvminstruction__t__" ],
    [ "hdvmmethod_t_", "structhdvmmethod__t__.html", "structhdvmmethod__t__" ],
    [ "hdvmmethodanalysis_t_", "structhdvmmethodanalysis__t__.html", "structhdvmmethodanalysis__t__" ],
    [ "hdvmstringanalysis_t_", "structhdvmstringanalysis__t__.html", "structhdvmstringanalysis__t__" ]
];