var hierarchy =
[
    [ "shuriken::disassembler::dex::_exception_data", "structshuriken_1_1disassembler_1_1dex_1_1__exception__data.html", null ],
    [ "shuriken::disassembler::dex::_handler_data", "structshuriken_1_1disassembler_1_1dex_1_1__handler__data.html", null ],
    [ "shuriken::analysis::dex::Analysis", "classshuriken_1_1analysis_1_1dex_1_1Analysis.html", null ],
    [ "shuriken::parser::dex::AnnotationDirectoryItem", "classshuriken_1_1parser_1_1dex_1_1AnnotationDirectoryItem.html", null ],
    [ "shuriken::parser::dex::AnnotationElement", "classshuriken_1_1parser_1_1dex_1_1AnnotationElement.html", null ],
    [ "basic_blocks_t_", "structbasic__blocks__t__.html", null ],
    [ "shuriken::analysis::dex::BasicBlocks", "classshuriken_1_1analysis_1_1dex_1_1BasicBlocks.html", null ],
    [ "shuriken::analysis::dex::ClassAnalysis", "classshuriken_1_1analysis_1_1dex_1_1ClassAnalysis.html", null ],
    [ "shuriken::parser::dex::ClassDataItem", "classshuriken_1_1parser_1_1dex_1_1ClassDataItem.html", null ],
    [ "shuriken::parser::dex::ClassDef", "classshuriken_1_1parser_1_1dex_1_1ClassDef.html", null ],
    [ "shuriken::parser::dex::ClassDef::classdefstruct_t", "structshuriken_1_1parser_1_1dex_1_1ClassDef_1_1classdefstruct__t.html", null ],
    [ "shuriken::parser::dex::CodeItemStruct::code_item_struct_t", "structshuriken_1_1parser_1_1dex_1_1CodeItemStruct_1_1code__item__struct__t.html", null ],
    [ "shuriken::parser::dex::CodeItemStruct", "classshuriken_1_1parser_1_1dex_1_1CodeItemStruct.html", null ],
    [ "shuriken::deref_iterator_range< T >", "structshuriken_1_1deref__iterator__range.html", null ],
    [ "shuriken::parser::dex::DexClasses", "classshuriken_1_1parser_1_1dex_1_1DexClasses.html", null ],
    [ "shuriken::disassembler::dex::DexDisassembler", "classshuriken_1_1disassembler_1_1dex_1_1DexDisassembler.html", null ],
    [ "shuriken::parser::dex::DexFields", "classshuriken_1_1parser_1_1dex_1_1DexFields.html", null ],
    [ "shuriken::parser::dex::DexHeader", "classshuriken_1_1parser_1_1dex_1_1DexHeader.html", null ],
    [ "shuriken::parser::dex::DexHeader::dexheader_t", "structshuriken_1_1parser_1_1dex_1_1DexHeader_1_1dexheader__t.html", null ],
    [ "shuriken::parser::dex::DexMapList", "classshuriken_1_1parser_1_1dex_1_1DexMapList.html", null ],
    [ "shuriken::parser::dex::DexMethods", "classshuriken_1_1parser_1_1dex_1_1DexMethods.html", null ],
    [ "shuriken::disassembler::dex::DexOpcodes", "classshuriken_1_1disassembler_1_1dex_1_1DexOpcodes.html", null ],
    [ "shuriken::parser::dex::DexProtos", "classshuriken_1_1parser_1_1dex_1_1DexProtos.html", null ],
    [ "shuriken::parser::dex::DexStrings", "classshuriken_1_1parser_1_1dex_1_1DexStrings.html", null ],
    [ "shuriken::parser::dex::DexTypes", "classshuriken_1_1parser_1_1dex_1_1DexTypes.html", null ],
    [ "shuriken::disassembler::dex::DisassembledMethod", "classshuriken_1_1disassembler_1_1dex_1_1DisassembledMethod.html", null ],
    [ "shuriken::disassembler::dex::Disassembler", "classshuriken_1_1disassembler_1_1dex_1_1Disassembler.html", null ],
    [ "shuriken::analysis::dex::DVMBasicBlock", "classshuriken_1_1analysis_1_1dex_1_1DVMBasicBlock.html", null ],
    [ "dvmdisassembled_method_t_", "structdvmdisassembled__method__t__.html", null ],
    [ "dvmexceptions_data_t_", "structdvmexceptions__data__t__.html", null ],
    [ "dvmhandler_data_t_", "structdvmhandler__data__t__.html", null ],
    [ "shuriken::parser::dex::DVMType", "classshuriken_1_1parser_1_1dex_1_1DVMType.html", [
      [ "shuriken::parser::dex::DVMArray", "classshuriken_1_1parser_1_1dex_1_1DVMArray.html", null ],
      [ "shuriken::parser::dex::DVMClass", "classshuriken_1_1parser_1_1dex_1_1DVMClass.html", null ],
      [ "shuriken::parser::dex::DVMFundamental", "classshuriken_1_1parser_1_1dex_1_1DVMFundamental.html", null ],
      [ "shuriken::parser::dex::Unknown", "classshuriken_1_1parser_1_1dex_1_1Unknown.html", null ]
    ] ],
    [ "shuriken::parser::dex::EncodedAnnotation", "classshuriken_1_1parser_1_1dex_1_1EncodedAnnotation.html", null ],
    [ "shuriken::parser::dex::EncodedArray", "classshuriken_1_1parser_1_1dex_1_1EncodedArray.html", null ],
    [ "shuriken::parser::dex::EncodedCatchHandler", "classshuriken_1_1parser_1_1dex_1_1EncodedCatchHandler.html", null ],
    [ "shuriken::parser::dex::EncodedField", "classshuriken_1_1parser_1_1dex_1_1EncodedField.html", null ],
    [ "shuriken::parser::dex::EncodedMethod", "classshuriken_1_1parser_1_1dex_1_1EncodedMethod.html", null ],
    [ "shuriken::parser::dex::EncodedTypePair", "structshuriken_1_1parser_1_1dex_1_1EncodedTypePair.html", null ],
    [ "shuriken::parser::dex::EncodedValue", "classshuriken_1_1parser_1_1dex_1_1EncodedValue.html", null ],
    [ "std::exception", null, [
      [ "exceptions::InvalidInstructionException", "classexceptions_1_1InvalidInstructionException.html", null ]
    ] ],
    [ "shuriken::analysis::dex::ExternalClass", "classshuriken_1_1analysis_1_1dex_1_1ExternalClass.html", null ],
    [ "shuriken::analysis::dex::ExternalField", "classshuriken_1_1analysis_1_1dex_1_1ExternalField.html", null ],
    [ "shuriken::analysis::dex::ExternalMethod", "classshuriken_1_1analysis_1_1dex_1_1ExternalMethod.html", null ],
    [ "std::false_type", null, [
      [ "shuriken::is_reference_wrapper< T::value_type >", "structshuriken_1_1is__reference__wrapper.html", [
        [ "shuriken::is_container_of_reference_wrapper< T, std::void_t< typename T::value_type > >", "structshuriken_1_1is__container__of__reference__wrapper_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1value__type_01_4_01_4.html", null ]
      ] ],
      [ "shuriken::is_container_of_reference_wrapper< T, typename >", "structshuriken_1_1is__container__of__reference__wrapper.html", null ],
      [ "shuriken::is_reference_wrapper< T >", "structshuriken_1_1is__reference__wrapper.html", null ]
    ] ],
    [ "shuriken::analysis::dex::FieldAnalysis", "classshuriken_1_1analysis_1_1dex_1_1FieldAnalysis.html", null ],
    [ "shuriken::parser::dex::FieldAnnotation", "structshuriken_1_1parser_1_1dex_1_1FieldAnnotation.html", null ],
    [ "shuriken::parser::dex::FieldID", "classshuriken_1_1parser_1_1dex_1_1FieldID.html", null ],
    [ "hdvm_class_field_idx_t_", "structhdvm__class__field__idx__t__.html", null ],
    [ "hdvm_class_idx_t_", "structhdvm__class__idx__t__.html", null ],
    [ "hdvm_class_method_idx_t_", "structhdvm__class__method__idx__t__.html", null ],
    [ "hdvm_classxref_t_", "structhdvm__classxref__t__.html", null ],
    [ "hdvm_method_idx_t_", "structhdvm__method__idx__t__.html", null ],
    [ "hdvm_reftype_method_idx_t_", "structhdvm__reftype__method__idx__t__.html", null ],
    [ "hdvmbasicblock_t_", "structhdvmbasicblock__t__.html", null ],
    [ "hdvmclass_t", "structhdvmclass__t.html", null ],
    [ "hdvmclassanalysis_t_", "structhdvmclassanalysis__t__.html", null ],
    [ "hdvmfield_t_", "structhdvmfield__t__.html", null ],
    [ "hdvmfieldanalysis_t_", "structhdvmfieldanalysis__t__.html", null ],
    [ "hdvminstruction_t_", "structhdvminstruction__t__.html", null ],
    [ "hdvmmethod_t_", "structhdvmmethod__t__.html", null ],
    [ "hdvmmethodanalysis_t_", "structhdvmmethodanalysis__t__.html", null ],
    [ "hdvmstringanalysis_t_", "structhdvmstringanalysis__t__.html", null ],
    [ "shuriken::disassembler::dex::Instruction", "classshuriken_1_1disassembler_1_1dex_1_1Instruction.html", [
      [ "shuriken::disassembler::dex::DalvikIncorrectInstruction", "classshuriken_1_1disassembler_1_1dex_1_1DalvikIncorrectInstruction.html", null ],
      [ "shuriken::disassembler::dex::FillArrayData", "classshuriken_1_1disassembler_1_1dex_1_1FillArrayData.html", null ],
      [ "shuriken::disassembler::dex::Instruction00x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction00x.html", null ],
      [ "shuriken::disassembler::dex::Instruction10t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction10t.html", null ],
      [ "shuriken::disassembler::dex::Instruction10x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction10x.html", null ],
      [ "shuriken::disassembler::dex::Instruction11n", "classshuriken_1_1disassembler_1_1dex_1_1Instruction11n.html", null ],
      [ "shuriken::disassembler::dex::Instruction11x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction11x.html", null ],
      [ "shuriken::disassembler::dex::Instruction12x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction12x.html", null ],
      [ "shuriken::disassembler::dex::Instruction20bc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction20bc.html", null ],
      [ "shuriken::disassembler::dex::Instruction20t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction20t.html", null ],
      [ "shuriken::disassembler::dex::Instruction21c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21c.html", null ],
      [ "shuriken::disassembler::dex::Instruction21h", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21h.html", null ],
      [ "shuriken::disassembler::dex::Instruction21s", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21s.html", null ],
      [ "shuriken::disassembler::dex::Instruction21t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction21t.html", null ],
      [ "shuriken::disassembler::dex::Instruction22b", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22b.html", null ],
      [ "shuriken::disassembler::dex::Instruction22c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22c.html", null ],
      [ "shuriken::disassembler::dex::Instruction22cs", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22cs.html", null ],
      [ "shuriken::disassembler::dex::Instruction22s", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22s.html", null ],
      [ "shuriken::disassembler::dex::Instruction22t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22t.html", null ],
      [ "shuriken::disassembler::dex::Instruction22x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction22x.html", null ],
      [ "shuriken::disassembler::dex::Instruction23x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction23x.html", null ],
      [ "shuriken::disassembler::dex::Instruction30t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction30t.html", null ],
      [ "shuriken::disassembler::dex::Instruction31c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31c.html", null ],
      [ "shuriken::disassembler::dex::Instruction31i", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31i.html", null ],
      [ "shuriken::disassembler::dex::Instruction31t", "classshuriken_1_1disassembler_1_1dex_1_1Instruction31t.html", null ],
      [ "shuriken::disassembler::dex::Instruction32x", "classshuriken_1_1disassembler_1_1dex_1_1Instruction32x.html", null ],
      [ "shuriken::disassembler::dex::Instruction35c", "classshuriken_1_1disassembler_1_1dex_1_1Instruction35c.html", null ],
      [ "shuriken::disassembler::dex::Instruction3rc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction3rc.html", null ],
      [ "shuriken::disassembler::dex::Instruction45cc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction45cc.html", null ],
      [ "shuriken::disassembler::dex::Instruction4rcc", "classshuriken_1_1disassembler_1_1dex_1_1Instruction4rcc.html", null ],
      [ "shuriken::disassembler::dex::Instruction51l", "classshuriken_1_1disassembler_1_1dex_1_1Instruction51l.html", null ],
      [ "shuriken::disassembler::dex::PackedSwitch", "classshuriken_1_1disassembler_1_1dex_1_1PackedSwitch.html", null ],
      [ "shuriken::disassembler::dex::SparseSwitch", "classshuriken_1_1disassembler_1_1dex_1_1SparseSwitch.html", null ]
    ] ],
    [ "shuriken::disassembler::dex::InstructionUtils", "classshuriken_1_1disassembler_1_1dex_1_1InstructionUtils.html", null ],
    [ "shuriken::deref_iterator_range< T >::iterator", "structshuriken_1_1deref__iterator__range_1_1iterator.html", null ],
    [ "shuriken::iterator_range< IteratorT >", "classshuriken_1_1iterator__range.html", null ],
    [ "shuriken::disassembler::dex::LinearSweepDisassembler", "classshuriken_1_1disassembler_1_1dex_1_1LinearSweepDisassembler.html", null ],
    [ "shuriken::parser::dex::DexMapList::map_item", "structshuriken_1_1parser_1_1dex_1_1DexMapList_1_1map__item.html", null ],
    [ "shuriken::analysis::dex::MethodAnalysis", "classshuriken_1_1analysis_1_1dex_1_1MethodAnalysis.html", null ],
    [ "shuriken::parser::dex::MethodAnnotation", "structshuriken_1_1parser_1_1dex_1_1MethodAnnotation.html", null ],
    [ "shuriken::parser::dex::MethodID", "classshuriken_1_1parser_1_1dex_1_1MethodID.html", null ],
    [ "shuriken::parser::dex::ParameterAnnotation", "structshuriken_1_1parser_1_1dex_1_1ParameterAnnotation.html", null ],
    [ "shuriken::parser::dex::Parser", "classshuriken_1_1parser_1_1dex_1_1Parser.html", null ],
    [ "shuriken::parser::dex::ProtoID", "classshuriken_1_1parser_1_1dex_1_1ProtoID.html", null ],
    [ "shuriken::common::ShurikenStream", "classshuriken_1_1common_1_1ShurikenStream.html", null ],
    [ "shuriken::analysis::dex::StringAnalysis", "classshuriken_1_1analysis_1_1dex_1_1StringAnalysis.html", null ],
    [ "std::true_type", null, [
      [ "shuriken::is_reference_wrapper< std::reference_wrapper< U > >", "structshuriken_1_1is__reference__wrapper_3_01std_1_1reference__wrapper_3_01U_01_4_01_4.html", null ]
    ] ],
    [ "shuriken::parser::dex::TryItem", "structshuriken_1_1parser_1_1dex_1_1TryItem.html", null ],
    [ "shuriken::dex::Utils", "classshuriken_1_1dex_1_1Utils.html", null ]
];